version: '3'

services:
  api_doutor_ie:
    container_name: api_doutor_ie
    image: leandrocosta91/api-doutor-ie:1.0
    volumes:
      - ./:/var/www/
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
      - .docker/nginx/conf.d:/etc/nginx/conf.d
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      APP_NAME: "${APP_NAME}"
      APP_ENV: "${APP_ENV}"
      APP_KEY: "${APP_KEY}"
      APP_DEBUG: "${APP_DEBUG}"
      APP_URL: "${APP_URL}"
      LOG_CHANNEL: "${LOG_CHANNEL}"
      DB_CONNECTION: "${DB_CONNECTION}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      BROADCAST_DRIVER: "${BROADCAST_DRIVER}"
      CACHE_DRIVER: "${CACHE_DRIVER}"
      SESSION_DRIVER: "${SESSION_DRIVER}"
      SESSION_LIFETIME: "${SESSION_LIFETIME}"
    networks:
      - app-network

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: "${DB_PORT}"
      PMA_USER: "${DB_USERNAME}"
      PMA_PASSWORD: "${DB_PASSWORD}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysqldata:
    driver: local