FROM php:8.1-fpm

USER root

WORKDIR /var/www

RUN curl -sL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh
RUN ["sh",  "./nodesource_setup.sh"]

RUN apt-get update \
	# gd
	&& apt-get install -y \
	build-essential \
	openssl \
	libfreetype6-dev \
	libjpeg-dev \
	libpng-dev \
	libwebp-dev \
	zlib1g-dev \
	libzip-dev \
	gcc \
	g++ \
	make \
	vim \
	unzip \
	curl \
	git \
	jpegoptim \
	optipng \
	pngquant \
	gifsicle \
	locales \
	libonig-dev \
	nodejs \
	nginx \
	&& docker-php-ext-configure gd  \
	&& docker-php-ext-install gd \
	# gmp
	&& apt-get install -y --no-install-recommends libgmp-dev \
	&& docker-php-ext-install gmp \
	# pdo_mysql
	&& docker-php-ext-install pdo_mysql mbstring \
	# pdo
	&& docker-php-ext-install pdo \
	# opcache
	&& docker-php-ext-enable opcache \
	# exif
    && docker-php-ext-install exif \
    && docker-php-ext-install sockets \
    && docker-php-ext-install pcntl \
    && docker-php-ext-install bcmath \
	# zip
	&& docker-php-ext-install zip \
	&& apt-get autoclean -y \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /tmp/pear/


COPY build.dev.sh /var/www

RUN chmod +rwx /var/www

RUN chmod -R 777 /var/www

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
	&& php composer-setup.php \
	&& php -r "unlink('composer-setup.php');" \
	&& mv composer.phar /usr/local/bin/composer

EXPOSE 80

RUN chmod +x build.dev.sh

CMD [ "sh", "./build.dev.sh" ]